server:
  port: 8088

spring:
  rabbitmq:
    host: 212.64.40.52
    port: 5672
    username: guest
    password: guest
    # 消息发送确认，确保消息发送到交换机
    publisher-confirms: true
    # 消息发送确认，确保消息到了队列，只有失败时触发
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: MANUAL