server:
  port: 8012

spring:
  application:
    name: study-stomp
  thymeleaf:
    mode: HTML5
    prefix: classpath:/html/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false