server:
  port: 8300

fdfs:
  so-timeout: 15000
  soTimeout: 15000
  connect-timeout: 15000
  connectTimeout: 15000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 10.100.32.63:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 50000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    min-idle-per-key: 5

nev:
  fdfs:
    enabled: true
    config_file: "config/fdfs_client_loc.conf"
    nginx_host: 10.100.32.63
    nginx_port: 8888
